#!/bin/bash -l 
#SBATCH -A mp309
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:10:00 
#SBATCH -J upc-HW3
#SBATCH -o output/upc-HW3.%j.out
#SBATCH -e output/upc-HW3.%j.err

# Parameters
P=3				# Number of UPC processes to run
INPUT=input/test		# Path to your input file
OUT_SERIAL=output/serial.out
OUT_PGEN=output/pgen.out
OUT_SSORTED=output/serial.sorted
OUT_PSORTED=output/pgen.sorted

cd ${PWD}

# Run program
srun -n 1 ./serial ${INPUT}
upcrun -n $P -shared-heap=1G ./pgen ${INPUT}


# Sort contigs in both output files to compare
sort ${OUT_SERIAL} ${OUT_SSORTED}
sort ${OUT_PGEN} ${OUT_PSORTED}

# diff -q <file1> <file2> will print nothing if both files are equal
# It will say "Files <file1> and <file2> differ" otherwise.
# Hint: remove -q option to show the lines that differ (not recommended when your output file is large)
diff -q ${OUT_SSORTED} ${OUT_PSORTED}


