#!/bin/bash -l 
#SBATCH -A mp309
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:30:00 
#SBATCH -J single-HW3
#SBATCH -o output/single-HW3.%j.out
#SBATCH -e output/single-HW3.%j.err


# Specify path to your input file here
INPUT=input/test
#INPUT=$SCRATCH/my_stripped_folder/largeinput

cd ${PWD}
for P in `seq 1 6`; do
	upcrun -n $P -shared-heap=1G ./pgen ${INPUT}
done
for P in `seq 7 12`; do
	upcrun -n $P -shared-heap=1G ./pgen ${INPUT}
done
for P in `seq 13 24`; do
	upcrun -n $P -shared-heap=1G ./pgen ${INPUT}
done


