#!/bin/bash -l 
#SBATCH -A mp309
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:10:00 
#SBATCH -J serial-HW3
#SBATCH -o output/serial-HW3.%j.out
#SBATCH -e output/serial-HW3.%j.err


INPUT=input/test

cd ${PWD}
srun -n 1 ./serial ${INPUT}

