#!/bin/bash -l
#SBATCH -A mp309
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:02:00
#SBATCH -J pgenTest
#SBATCH -o output/pgenTest.%j.out
#SBATCH -e output/pgenTest.%j.err

#INPUT=input/test
INPUT=$SCRATCH/my_stripped_folder/largeinput
EXE=./pgen
export GASNET_BACKTRACE=1

cd ${PWD}

upcrun -n 4 -N 1 ${EXE} ${INPUT} > output/commandline.txt

cat output/pgen-*.out > output/pgen.out
sort output/pgen.out > output/pgen.sorted
